spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/footballdemo
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: create.sql

logging:
  level:
    org:
      springframework:
        web: DEBUG

application:
  footballapikey: 95897fa9902e49f986e937c4c0f5c529
  competitionsurl: http://api.football-data.org/v2/competitions/
  teamsurl: http://api.football-data.org/v2/teams/


